backend:
  name: github
  repo: oscsyn/ths-international-reception
media_folder: static/uploads
public_folder: uploads

collections:
  - name: "addFaq"
    label: "Add Faq"
    folder: "src/markdown-pages/faqs"
    create: true
    fields:
      - { name: "category", label: "Category", widget: "string", required: true }
      - label: Question
        name: question
        widget: list
        fields:
          - { name: "title", label: "Title", widget: "string", required: true }
          - { name: "description", label: "Description", widget: "text", required: true }

