backend:
  name: github
  repo: oscsyn/ths-international-reception
media_folder: src/images
public_folder: images

collections:
  - name: "addFaq"
    label: "FAQ"
    folder: "src/markdown-pages/faqs"
    create: true
    identifier_field: category
    fields:
      - { name: "category", label: "Category", widget: "string", required: true }
      - { name: "type", label: "Type", widget: "hidden", default: "faq"}
      - label: Question
        name: question
        widget: list
        fields:
          - { name: "title", label: "Title", widget: "string", required: true }
          - { name: "description", label: "Description", widget: "markdown", required: true }

  - name: "addNews"
    label: "News"
    folder: "src/markdown-pages/news"
    create: true
    identifier_field: title
    fields:
      - { name: "title", label: "Title", widget: "string", required: true }
      - { name: "thumbnail", label: "Featured Image", widget: "image", default:"/images/kthnews.png" }
      - { name: "description", label: "Description", widget: "markdown", required: true }
      - { name: "preview", label: "Preview", widget: "markdown", required: true }
      - { name: "type", label: "Type", widget: "hidden", default: "news"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/markdown-pages/faq.md"
        label: "faq-markdown"
        name: faq
        fields:
          - { name: "type", label: "Type", widget: "hidden", default: "faq-page"}
          - label: Categories
            name: categories
            widget: list
            fields:
              - { name: "category", label: "Category", widget: "string", required: true }
              - label: Question
                name: questions
                widget: list
                fields:
                  - { name: "title", label: "Title", widget: "string", required: true }
                  - { name: "description", label: "Description", widget: "markdown", required: true }
      - file: "src/markdown-pages/about.md"
        label: "about-markdown"
        name: about
        fields:
          - { name: "type", label: "Type", widget: "hidden", default: "about-page"}
          - { name: "content", label: "Content", widget: "markdown", required: true }
      - file: "src/markdown-pages/archive.md"
        label: "archive-markdown"
        name: archive
        fields:
          - { name: "type", label: "Type", widget: "hidden", default: "archive-page"}
          - { name: "content", label: "Content", widget: "markdown", required: true }
      - file: "src/markdown-pages/buddies.md"
        label: "buddies-markdown"
        name: buddies
        fields:
          - { name: "type", label: "Type", widget: "hidden", default: "buddies-page"}
          - { name: "content", label: "Content", widget: "markdown", required: true }
      - file: "src/markdown-pages/team.md"
        label: "team-markdown"
        name: team
        fields:
          - { name: "type", label: "Type", widget: "hidden", default: "team-page"}
          - { name: "content", label: "Content", widget: "markdown", required: true }
      - file: "src/markdown-pages/vision.md"
        label: "vision-markdown"
        name: vision
        fields:
          - { name: "type", label: "Type", widget: "hidden", default: "vision-page"}
          - { name: "content", label: "Content", widget: "markdown", required: true }