backend:
  name: github
  repo: oscsyn/ths-international-reception
media_folder: static/uploads
public_folder: uploads

collections:
  - name: "addFaq"
    label: "Add Faq"
    folder: "src/pages/faqs"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - { name: "category", label: "Category", widget: "string", required: true }
      - { name: "title", label: "Title", widget: "string", required: true }
      - { name: "description", label: "Description", widget: "string", required: true }
      - { name: "type", label: "Type", widget: hidden, default: "faq"}

