backend:
  name: github
  repo: oscsyn/ths-international-reception
media_folder: static/uploads
public_folder: uploads

collections:
  - name: "addFaq"
    label: "FAQ"
    folder: "src/markdown-pages/faqs"
    create: true
    identifier_field: category
    fields:
      - { name: "category", label: "Category", widget: "string", required: true }
      - { name: "type", label: "Type", widget: "hidden", default: "faq"}
      - label: Question
        name: question
        widget: list
        fields:
          - { name: "title", label: "Title", widget: "string", required: true }
          - { name: "description", label: "Description", widget: "markdown", required: true }

  - name: "addNews"
    label: "News"
    folder: "src/markdown-pages/news"
    create: true
    identifier_field: title
    fields:
      - { name: "title", label: "Title", widget: "string", required: true }
      - { name: "thumbnail", label: "Featured Image", widget: "image", default:"/uploads/kthnews.png" }
      - { name: "description", label: "Description", widget: "markdown", required: true }
      - { name: "preview", label: "Preview", widget: "markdown", required: true }
      - { name: "type", label: "Type", widget: "hidden", default: "news"}